#!/bin/sh

sxhkd &
#exec setxkbmap dk &
numlockx &
/home/null/.screenlayout/bspwm_3_mon.sh
#light-locker-settings &

bspc config border_width        1
bspc config window_gap          25

# -----------------------------------------------------------------

bspc monitor DP1 -d DEV
bspc monitor HDMI2 -d WEB TERM FILES RAND SOC MEDIA EXTR REMOTE

# -----------------------------------------------------------------

/usr/bin/numlockx on &

bspc config top_padding 14

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#2e3436"
bspc config active_border_color "#817267"
bspc config focused_border_color "#eeeeec"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1


# Rules
bspc rule -a Skype pseudo_tiled=on
bspc rule -a wine pseudo_tiled=on floating=on
bspc rule -a rofi pseudo_tiled=on
bspc rule -a Infinit pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a sun-awt-X11-XFramePeer pseudo_tiled=on
bspc rule -a Renoise pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off
bspc rule -a Wine manage=off
bspc rule -a VirtualBox state=floating

# panel &

sleep 1
feh --bg-scale /home/null/Pictures/green.jpg  &
# dropbox &
syncthing &
sleep 2
run_keybase &

sleep 1
/home/null/.config/bspwm/start.sh &

compton &
sleep 1
radiotray &
#insync start &
lxappearance &
sleep 5
thunderbird &




exec wmname LG3D &
sleep 3
exec veracrypt -v /home/null/Documents/elk_stack_videos.tar.gz  /mnt/veracrypt2 &
sleep 1
/home/null/Documents/get_scripts/i3_lock_script.sh

